ticketing:
    resource: "@TicketingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ticketing
    requirements:
      _locale: en|fr


oc_core:
    resource: "@CoreBundle/Resources/config/routing.yml"