services:

  ticketing.payment.stripe:
    class: TicketingBundle\Services\Stripe\PaymentStripe
    arguments:
      - "%stripeAPIKey%"

  ticketing.mail.swiftmailer:
      class: TicketingBundle\Services\Mailer\MailBySwiftmailer
      arguments:
       - "@mailer"
       - "@twig"
       - "%mailer_user%"
       - "@translator"

