services:


  ticketing.paiement.stripe:
    class: TicketingBundle\Stripe\PaiementStripe
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@mailer"
      - "@templating"
      - $adminEmail: 'mickael@parlow-co.com'